blank_issues_enabled: true
contact_links:
  - name: Documentation
    url: https://github.com/Critical-Impact/symfony1-inspections
    about: Check the README file in the first place.
  - name: Getting Help
    url: https://github.com/Critical-Impact/symfony1-inspections
    about: Check if you search for a help in plugin development.
